import { createHmac } from "node:crypto";
import type { RowDataPacket } from "mysql2";
import { z } from "zod";
import { adminConfigured, setAdminSession, verifyPassword } from "@/lib/admin/auth";
import { databaseConfigured } from "@/lib/custom-store/db";
import { mysqlDb } from "@/lib/custom-store/mysql";
import { isStoreOrigin } from "@/lib/request-origin";
const loginInput = z.object({ username: z.string().max(80), password: z.string().max(200) });
export async function POST(request: Request) { if (!isStoreOrigin(request)) return Response.json({ error: "Invalid request origin." }, { status: 403 }); if (!adminConfigured() || !databaseConfigured()) return Response.json({ error: "Admin setup is incomplete." }, { status: 503 }); const parsed = loginInput.safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: "Invalid sign-in." }, { status: 400 }); const ipHash = createHmac("sha256", process.env.ADMIN_SESSION_SECRET!).update((request.headers.get("x-forwarded-for") || "unknown").split(",")[0].trim()).digest("hex"); const sql = mysqlDb(); const [rows] = await sql.execute<RowDataPacket[]>("SELECT attempts,blocked_until FROM admin_login_attempts WHERE ip_hash=?", [ipHash]); const previous = rows[0]; if (previous?.blocked_until && new Date(previous.blocked_until).getTime() > Date.now()) return Response.json({ error: "Too many attempts. Try again later." }, { status: 429 }); if (!verifyPassword(parsed.data.username, parsed.data.password)) { const count = Number(previous?.attempts || 0) + 1; await sql.execute("INSERT INTO admin_login_attempts (ip_hash,attempts,blocked_until) VALUES (?,?,?) ON DUPLICATE KEY UPDATE attempts=VALUES(attempts),blocked_until=VALUES(blocked_until)", [ipHash, count, count >= 5 ? new Date(Date.now() + 15 * 60_000) : null]); return Response.json({ error: "Incorrect ID or password." }, { status: 401 }); } await sql.execute("DELETE FROM admin_login_attempts WHERE ip_hash=?", [ipHash]); await setAdminSession(); return Response.json({ ok: true }, { headers: { "Cache-Control": "no-store" } }); }
