import type { Collection, Product } from "./types";
// Demonstration catalog only. Replace with real photographs and measurements before launch.
const entries = [
  [
    "washed-denim-jacket",
    "The washed denim jacket",
    "Jackets",
    "Unisex",
    "M",
    "Blue",
    4250,
    "Excellent",
    "denim-jacket",
    "Denim,Streetwear",
    "denim-edit,outerwear",
    "Cotton",
    "Chest:58,Length:65,Shoulder:49,Sleeve:61",
  ],
  [
    "everyday-charcoal-hoodie",
    "The everyday hoodie",
    "Hoodies",
    "Unisex",
    "L",
    "Charcoal",
    3200,
    "Very good",
    "hoodie",
    "Streetwear,Essentials",
    "street-essentials",
    "Cotton blend",
    "Chest:62,Length:70,Shoulder:56,Sleeve:60",
  ],
  [
    "faded-graphic-tee",
    "The white graphic tee",
    "T-shirts",
    "Unisex",
    "L",
    "White",
    1850,
    "Good",
    "graphic-tee",
    "Vintage,Streetwear",
    "street-essentials",
    "Cotton",
    "Chest:56,Length:72,Shoulder:50,Sleeve:23",
  ],
  [
    "relaxed-blue-denim",
    "The relaxed cargo denim",
    "Jeans",
    "Unisex",
    "32",
    "Blue",
    3600,
    "Excellent",
    "jeans",
    "Denim,Essentials",
    "denim-edit",
    "Cotton",
    "Waist:41,Rise:30,Inseam:78,Leg opening:21",
  ],
  [
    "olive-workwear-jacket",
    "The workwear jacket",
    "Jackets",
    "Men",
    "L",
    "Olive",
    4800,
    "Very good",
    "workwear-jacket",
    "Workwear,Streetwear",
    "outerwear",
    "Cotton canvas",
    "Chest:61,Length:73,Shoulder:51,Sleeve:63",
  ],
  [
    "striped-weekend-shirt",
    "The weekend shirt",
    "Shirts",
    "Men",
    "M",
    "Blue",
    2400,
    "Like new",
    "striped-shirt",
    "Essentials",
    "street-essentials",
    "Cotton",
    "Chest:56,Length:75,Shoulder:46,Sleeve:62",
  ],
  [
    "soft-knit-cardigan",
    "The soft knit cardigan",
    "Knitwear",
    "Women",
    "S",
    "Cream",
    2900,
    "Excellent",
    "cardigan",
    "Vintage,Essentials",
    "soft-layers",
    "Cotton blend",
    "Chest:49,Length:58,Shoulder:42,Sleeve:58",
  ],
  [
    "tailored-neutral-trousers",
    "The relaxed trouser",
    "Trousers",
    "Women",
    "28",
    "Beige",
    2800,
    "Very good",
    "trousers",
    "Essentials",
    "soft-layers",
    "Cotton blend",
    "Waist:36,Rise:29,Inseam:73,Leg opening:23",
  ],
] as const;
export const sampleProducts: Product[] = entries.map((p, index) => ({
  id: `sample-${index + 1}`,
  handle: p[0],
  title: p[1],
  category: p[2],
  gender: p[3],
  sizeLabel: p[4],
  color: p[5],
  price: p[6],
  condition: p[7],
  brand: "Unbranded",
  currency: "PKR",
  description:
    "An easy-going piece with a lived-in character. Style it your way, wear it often, and give it a new chapter.",
  style: p[9].split(","),
  collection: [...p[10].split(","), ...(index < 6 ? ["preview-drop"] : [])],
  tags: p[9].toLowerCase().split(","),
  measurements: Object.fromEntries(
    p[12].split(",").map((x) => {
      const [k, v] = x.split(":");
      return [k, Number(v)];
    }),
  ),
  material: p[11],
  stock: index === 7 ? 0 : 1,
  createdAt: `2026-09-${String(27 - index).padStart(2, "0")}T10:00:00Z`,
  sample: true,
  conditionNotes:
    index === 2
      ? "Even fading throughout. A small mark near the lower hem is included as a sample condition disclosure."
      : index === 1
        ? "Soft surface wear and light pilling at the cuffs. No structural damage in this sample description."
        : "Sample grading and measurements for preview purposes. Actual item details will be supplied with real inventory.",
  defects:
    index === 2
      ? [
          "Small mark near lower hem (sample disclosure; real defect photography required before sale).",
        ]
      : [],
  images: [
    {
      src: `/images/${p[8]}.jpg`,
      alt: `${p[1]} — illustrative preview photograph`,
      label: "Editorial preview",
    },
    {
      src: `/images/${p[8]}.jpg`,
      alt: `Closer crop of ${p[1]} — same preview photograph`,
      label: "Detail crop",
    },
  ],
}));
export const sampleCollections: Collection[] = [
  {
    id: "preview-drop",
    handle: "preview-drop",
    title: "The first edit",
    description:
      "A preview of what’s to come. Easy layers, lived-in denim, and pieces with personality.",
    image: "/images/denim-jacket.jpg",
    isDrop: true,
  },
  {
    id: "denim-edit",
    handle: "denim-edit",
    title: "The denim edit",
    description: "Good denim only gets more interesting.",
    image: "/images/jeans.jpg",
  },
  {
    id: "outerwear",
    handle: "outerwear",
    title: "Outer layers",
    description: "The pieces that pull everything together.",
    image: "/images/workwear-jacket.jpg",
  },
  {
    id: "street-essentials",
    handle: "street-essentials",
    title: "Street essentials",
    description: "Everyday pieces. Anything but ordinary.",
    image: "/images/hoodie.jpg",
  },
  {
    id: "soft-layers",
    handle: "soft-layers",
    title: "Soft layers",
    description: "A slower pace. An easier silhouette.",
    image: "/images/cardigan.jpg",
  },
].map((c) => ({
  ...c,
  productIds: sampleProducts
    .filter((p) => p.collection.includes(c.id))
    .map((p) => p.id),
}));
