-- Existing verified catalog, excluding the unfinished test T-shirt.
-- Run after setup.sql, once only. Stable IDs match the read-only fallback catalog.
insert into store_private.products
  (id, handle, title, brand, description, category, gender, condition, condition_notes,
   size_label, color, price, compare_at_price, stock, images, collections)
values
  ('7c000000-0000-4000-8000-000000000001', 'comptoir-des-cotonniers-piece', 'Comptoir des Cotonniers Piece', 'Comptoir des Cotonniers', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Good', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 2000, 4000, 1, '[{"src":"/images/products/Comptoir_des_Cotonniers_try-on-preview.png","alt":"Comptoir des Cotonniers Piece","label":"Product photo"}]', '{the-edit}'),
  ('7c000000-0000-4000-8000-000000000002', 'dolce-gabbana-piece', 'Dolce & Gabbana Piece', 'Dolce & Gabbana', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Premium', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 2000, 4000, 1, '[{"src":"/images/products/Dolce_and_Gabbana_try-on-preview.png","alt":"Dolce & Gabbana Piece","label":"Product photo"}]', '{the-edit}'),
  ('7c000000-0000-4000-8000-000000000003', 'zara-basic-piece-1', 'Zara Basic Piece 1', 'Zara', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Good', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 2000, 4000, 1, '[{"src":"/images/products/Zara_Basic_try-on-preview-1.png","alt":"Zara Basic Piece 1","label":"Product photo"}]', '{the-edit}'),
  ('7c000000-0000-4000-8000-000000000004', 'zara-basic-piece-2', 'Zara Basic Piece 2', 'Zara', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Good', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 2000, 4000, 1, '[{"src":"/images/products/Zara_Basic_try-on-preview-2.png","alt":"Zara Basic Piece 2","label":"Product photo"}]', '{the-edit}'),
  ('7c000000-0000-4000-8000-000000000005', 'zara-basic-piece-3', 'Zara Basic Piece 3', 'Zara', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Good', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 2000, 4000, 1, '[{"src":"/images/products/Zara_Basic_try-on-preview-3.png","alt":"Zara Basic Piece 3","label":"Product photo"}]', '{the-edit}'),
  ('7c000000-0000-4000-8000-000000000006', 'zara-basic-piece-4', 'Zara Basic Piece 4', 'Zara', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Good', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 1100, 2200, 1, '[{"src":"/images/products/Zara_Basic_try-on-preview-4.png","alt":"Zara Basic Piece 4","label":"Product photo"}]', '{the-edit}'),
  ('7c000000-0000-4000-8000-000000000007', 'massimo-dutti-blue-piece', 'Massimo Dutti Blue Piece', 'Massimo Dutti', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Excellent', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 2000, 4000, 1, '[{"src":"/images/products/Massimo_Dutti_try-on-preview-blue.png","alt":"Massimo Dutti Blue Piece","label":"Product photo"}]', '{the-edit}'),
  ('7c000000-0000-4000-8000-000000000008', 'massimo-dutti-rust-piece', 'Massimo Dutti Rust Piece', 'Massimo Dutti', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Excellent', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 1500, 3000, 1, '[{"src":"/images/products/Massimo_Dutti_try-on-preview-rust.png","alt":"Massimo Dutti Rust Piece","label":"Product photo"}]', '{the-edit}'),
  ('7c000000-0000-4000-8000-000000000009', 'massimo-dutti-yellow-piece', 'Massimo Dutti Yellow Piece', 'Massimo Dutti', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Very good', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 1300, 2600, 1, '[{"src":"/images/products/Massimo_Dutti_try-on-preview-yellow.png","alt":"Massimo Dutti Yellow Piece","label":"Product photo"}]', '{the-edit}'),
  ('7c000000-0000-4000-8000-000000000010', 'zara-knit-piece', 'Zara Knit Piece', 'Zara', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Very good', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 1200, 2400, 1, '[{"src":"/images/products/Zara_Knit_try-on-preview.png","alt":"Zara Knit Piece","label":"Product photo"}]', '{the-edit}'),
  ('7c000000-0000-4000-8000-000000000011', 'zara-piece', 'Zara Piece', 'Zara', 'A one-of-a-kind pre-loved find. Please check the photos and ask us for measurements or condition details before ordering.', 'Clothing', 'Women', 'Excellent', 'Pre-loved piece. Detailed condition notes are being reviewed; contact us for specific details.', 'Ask for size', 'See photos', 1500, 3000, 0, '[{"src":"/images/products/Zara_try-on-preview.png","alt":"Zara Piece","label":"Product photo"}]', '{the-edit}')
on conflict (handle) do nothing;
