import type { RowDataPacket } from "mysql2";
import { ZodError } from "zod";
import { cookies } from "next/headers";
import { createHmac } from "node:crypto";
import { adminConfigured } from "@/lib/admin/auth";
import { databaseConfigured } from "@/lib/custom-store/db";
import { mysqlDb } from "@/lib/custom-store/mysql";
import { orderInput, placeOrder } from "@/lib/custom-store/orders";
import { isStoreOrigin } from "@/lib/request-origin";
export async function POST(request: Request) { if (!isStoreOrigin(request)) return Response.json({ error: "Invalid request origin." }, { status: 403 }); if (!databaseConfigured() || !adminConfigured()) return Response.json({ error: "Orders are not open yet. Please try again later." }, { status: 503 }); try { const raw = await request.text(); if (raw.length > 16000) return Response.json({ error: "Order request is too large." }, { status: 413 }); const input = orderInput.parse(JSON.parse(raw)); const ipHash = createHmac("sha256", process.env.ADMIN_SESSION_SECRET!).update((request.headers.get("x-forwarded-for") || "unknown").split(",")[0].trim()).digest("hex"); const sql = mysqlDb(); const [attempts] = await sql.execute<RowDataPacket[]>("SELECT attempts FROM checkout_attempts WHERE ip_hash=?", [ipHash]); const count = Number(attempts[0]?.attempts || 0) + 1; if (count > 10) return Response.json({ error: "Too many order attempts. Please try again later." }, { status: 429 }); await sql.execute("INSERT INTO checkout_attempts (ip_hash,attempts) VALUES (?,?) ON DUPLICATE KEY UPDATE attempts=VALUES(attempts)", [ipHash, count]); const order = await placeOrder(input); (await cookies()).set("thrift_last_order", `${order.id}.${input.idempotencyKey}`, { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax", path: "/order", maxAge: 60 * 60 * 24 * 30 }); return Response.json(order, { status: 201, headers: { "Cache-Control": "no-store" } }); } catch (error) { if (error instanceof ZodError) return Response.json({ error: error.issues[0]?.message || "Check your details." }, { status: 400 }); const message = error instanceof Error ? error.message : "Could not place the order."; if (/no longer available|appears twice|temporarily closed/.test(message)) return Response.json({ error: message }, { status: 409 }); return Response.json({ error: "Could not place your order. Please try again." }, { status: 503 }); } }
